env:
  browser: true
  es6: true
  mocha: true
  node: true
parser: babel-eslint
extends:
  - eslint:recommended
  - airbnb
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  prettier/prettier:
    - error
  complexity: error
  no-duplicate-imports: error
  no-eq-null: error
  no-eval: error
  no-implied-eval: error
  no-invalid-this: error
  no-underscore-dangle: 0
  no-shadow: error
  no-undefined: 0
  no-unused-expressions: 0
  class-methods-use-this: 0
  no-case-declarations: 0
  prefer-promise-reject-errors: error
  camelcase: 0
  no-param-reassign: 0
  no-return-assign: 0
